default: &default
  encoding: utf8
  pool: 5
  timeout: 10000

development:
  <<: *default
  database: db/development.sqlite3
  username: cycle3
  adapter: sqlite3

test:
  <<: *default
  database: db/test.sqlite3
  username: cycle3
  adapter: sqlite3

production:
  <<: *default
  adapter: postgresql
  database: shopprod